create function routine_name(P_USERID INTEGER )
RETURNS TABLE(DATE_OF_PURCHASE DATE, CLIENT_NAME VARCHAR(40))
return
        SELECT S.DATE, C.NAME FROM SALES S
        JOIN CLIENTS C ON S.CLIENTID=C.CLIENTID
        WHERE P_USERID=SALES.USERID;

create function getName(U_ID INTEGER)
returns varchar(20)
RETURN
    select USERNAME FROM FN45449.USERS WHERE
    USERID=U_ID;


