--User section
INSERT INTO FN45449.USERS(USERNAME, PASSWORD, EMPLOYEENAME) VALUES ('Azimov','azimov42_GSuite','Genadi Azimov');
INSERT INTO FN45449.USERS(USERNAME, PASSWORD, EMPLOYEENAME) VALUES ('Rl_stock','113TerraVague*','Blagovest Shopov');
INSERT INTO FN45449.USERS(USERNAME, PASSWORD, EMPLOYEENAME) VALUES ('august','BoriArg15&','Avgustina Borimirova');
INSERT INTO FN45449.USERS(USERNAME, PASSWORD, EMPLOYEENAME) VALUES ('Nedel','Kello@Plump215','Cvetalin Topalov');

--Product section
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A4 100P',3);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A4 80P',2.7);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A4 80P Hard Cover',5);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A5 100P',2.8);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A5 200P',4);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Notebook A5 80P',2.5);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Keyboard Gaming Fury Spitfire ',33.30);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Keyboard Gaming Hurricane',35);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('USB Flash SanDisk, 64 GB, USB 3.1, Black ',25.50);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('USB Flash Kingston, 128 GB, USB 3.0, Black ',44);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('External HDD Seagate 1TB, 2.5',109.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('External HDD ADATA HV320 Slim 1TB, Shock Sensor, 2.5',189);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Hub Multiport Hama USB Type-C',15);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Hub Lenovo Travel,',24.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Punching Bag Ringstar',64.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Lever Pull-up Sveltus',40);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Camping Tent Hellas',43);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Camp Gear Travel Mini ',42);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Tourist Bag Eagle ',39.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Pillow TED Memory',32.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Foam roller LiveUp, 33x14см, Black ',36.7);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Pillow Alcam Microfiber',61.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Professional calculator Texas Instruments TI-30XA ',22.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Scientific calculator Rebell SC2060',29.40);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('External sound card Sandberg USB',19.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES('Sound card Zik USB, 2.1 channels',8.88);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Wireless mouse Rebeltec THETA, USB mouse',12);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Wireless mouse C-TECH WLM-01WS , 1200DPI',9.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Adapter A+ USB tip C to HDMI ',19.99);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Video port adapter HAMA DVI-VGA ',12.52);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Cable Hama HDMI plug-DVI/D plug, 1.5 m ',15.89);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Adapter Hama Mini DisplayPort - HDMI, Black',25.29);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Black Tea Alin 20 pcs ',2.7);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Black Tea Vintage PASSION FRUIT',6.0);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Relax Tea Mika Matte',29.5);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Botanical Tea Fitness Energy, 120 g',29.00);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Botanical Royal - Black Tea & Cocoa',26);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Rosso Coffee Bianchi - 250 гр.',12.53);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Coffee Juan Valdez,Columbia , 250 гр.',19.90);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Coffee illy 250gr. ',16.70);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Coffee-espresso San Giusto, 0,250g.',13.65);
INSERT INTO FN45449.PRODUCTS(NAME, CATALOG_PRICE) VALUES ('Fitness lever Live-up 4 applications',42.30);
--Client section
--To do : add clients with UIC and VAT
INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Sevdalin Nikolov','RangSoft','010482093','BG010482093',null );
INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Trajan Daskalov',null ,null ,null ,'Varna, Troshevo, str. Elin Pelin, No 21');
INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Filip Andreev',null ,null ,null ,'Sofia, Красно село,ул. Дойран, Ном. 3');
INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Atanas Asenov',null,null ,null,'София, бул. Акад. Иван Гешов N102' );
INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Krasimir Evstratiev','JupiterElite',

--Sales & contents section
INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,6,6);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (1,2,1,185);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (1,5,10,20);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (1,11,10,45);

INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP ,2,4);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (2,6,1,33.30);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (2,7,1,25.5);

INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,3,4);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (22,24,1,40);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (22,25,1,64.99);


INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,2,6);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (23,29,1,32.99);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (23,35,4,94.99);

INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP ,6,1);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (24,11,15,70.99);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (24,4,3,132);


INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,3,1);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (25,43,25,600);


INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,3,2);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (26,46,20,500);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (26,50,20,370);

INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,1,6);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (61,48,5,125);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (61,42,10,140);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (61,2,3,140);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (61,32,5,110);
INSERT INTO FN45449.PRODUCTS_SOLD (SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (61,48,5,125);