SELECT * FROM FN45449.USERS;
select * from FN45449.CLIENTS;
SELECT * FROM FN45449.PRODUCTS;
SELECT * FROM FN45449.PRODUCTS_SOLD;
SELECT * FROM FN45449.SALES;

select NAME,FN45449.INCOME_FROM_CLIENT(CLIENTID) AS INCOME
    FROM FN45449.CLIENTS
    ORDER BY INCOME;

select EMPLOYEENAME,USERID from USERS_PRODUCTIVITY UP join USERS on EMPLOYEENAME=up.EMPLOYEE_NAME;


select * from CLIENT_PREFERENCES;
select * from USER_CONNECTIONS;
--Function tests
SELECT * FROM TABLE(FN45449.CHECK_PRODUCTS_IN_SALE(61))S;

SELECT * FROM TABLE(FN45449.CHECK_SOLD_TO_CLIENT(2))s;

SELECT * FROM TABLE (FN45449.LIST_ORDERS_FROM_CLIENT(4))R;

select * from Table(FN45449.SALES_FROM_USER_BY_DATE(1))R;

SELECT C.NAME,FN45449.INCOME_FROM_CLIENT(C.CLIENTID)
    FROM FN45449.CLIENTS C;

--Some testing
INSERT INTO FN45449.SALES(DATE_OF_COMPLETION, CLIENTID, USERID)
        VALUES (CURRENT_TIMESTAMP,6,23);
INSERT INTO FN45449.PRODUCTS_SOLD(SALEID, PRODUCTID, QUANTITY, TOTALPRICE)
        VALUES (42,44,120,312);
DELETE FROM FN45449.USERS WHERE USERID=22;

SELECT * FROM USER_CONNECTIONS;

INSERT INTO FN45449.CLIENTS(NAME, COMPANY_NAME, COMPANY_UIC, VAT, CLIENT_ADDRESS)
        VALUES ('Klomba gospodinov',null,'123456','BG123456','Astalavista');
UPDATE FN45449.CLIENTS C
    SET C.COMPANY_UIC='77777'
    WHERE NAME LIKE 'klomba%';
select * from FN45449.DUMMY;
select * from CLIENTS;
delete from CLIENTS where NAME like 'klomba%';



INSERT INTO FN45449.USERS(USERNAME, PASSWORD, EMPLOYEENAME) VALUES ('AZL','ARERETSDFDSF76*','ASD Azimov');
DELETE FROM USERS WHERE USERID=22;--Insert needed id

select * FROM TABLE(FN45449.INCOME_FROM_CLIENT(6))S  ;

VALUES (FN45449.INCOME_FROM_CLIENT(6));
