set schema FN45449;


--Връща сумарния оборот от продажби обработени от съответния служител
CREATE VIEW USERS_PRODUCTIVITY(Employee_Name,Revenue_from_sales)
AS
    SELECT EMPLOYEENAME,SUM(TOTALPRICE)
    FROM  FN45449.USERS U JOIN FN45449.SALES S ON S.USERID=U.USERID
    JOIN FN45449.PRODUCTS_SOLD PS ON S.SALEID = PS.SALEID
    GROUP BY U.EMPLOYEENAME, U.USERID;


--Всички потребители изведени с UserName за регистрация и име по лична карта
CREATE VIEW USERS_VIEW
AS
    SELECT USERNAME,EMPLOYEENAME
    FROM FN45449.USERS;

--Извежда за всеки клиент какво количество от продукти е купил досега
CREATE VIEW CLIENT_PREFERENCES(CLIENT_NAME, PRODUCT_NAME,AMOUNT)
AS
    SELECT C.NAME AS C_NAME,P.NAME AS P_NAME,SUM(QUANTITY)
        FROM FN45449.CLIENTS C,FN45449.PRODUCTS_SOLD PR,FN45449.PRODUCTS P,FN45449.SALES S
        WHERE P.PRODUCTID=PR.PRODUCTID AND S.CLIENTID=C.CLIENTID
        AND S.SALEID=PR.SALEID
        GROUP BY C.NAME, P.NAME;

--По userid показва броя на различните клиенти, с които той има контакт (обработил е поне една негова продажба).
CREATE VIEW USERS_BY_CLIENTS(USERID,COUNT)
AS
    SELECT U.USERID,COUNT(*) AS CNT FROM FN45449.USERS AS U
    JOIN FN45449.SALES AS S ON  S.USERID=U.USERID
    GROUP BY U.USERID;

--Използва горния view за да изкара информацията относно името на служителя.
--table names
CREATE OR REPLACE VIEW USER_CONNECTIONS(Employee_Name,Client_Count)
AS
    SELECT EMPLOYEENAME,V_TABLE.COUNT FROM
    FN45449.USERS U1,FN45449.USERS_BY_CLIENTS AS V_TABLE
    WHERE U1.USERID=V_TABLE.USERID;

--Извежда всички видове тетрадки в каталога
CREATE VIEW NOTEBOOKS(Notebook_Type)
AS
    SELECT NAME FROM FN45449.PRODUCTS
    WHERE NAME LIKE '%Notebook%';

CREATE VIEW HUBS(HUB_NAME)
AS
    SELECT NAME FROM FN45449.PRODUCTS
    WHERE NAME LIKE '%Hub%';

--Top employee this month
CREATE VIEW TOP_EMPLOYEE_MONTH
AS
    SELECT EMPLOYEENAME,SUM(TOTALPRICE) AS TOTAL
    FROM FN45449.USERS U, FN45449.PRODUCTS_SOLD PR, FN45449.SALES S
    WHERE U.USERID=S.USERID AND PR.SALEID=S.SALEID;

--Извеждане на продажби за дадена година.Пример с 2019.
CREATE VIEW SALES_2019
AS
    SELECT * FROM SALES
    WHERE YEAR(DATE_OF_COMPLETION)=2019;

